### ISSUE TITLE
Add subtitle blocks

### ISSUE THREAD

**Issue by LauraEhlis** [IRT-Open-Source/imsced#103]
The user is able to add new subtitle blocks at any position. When adding a new subtitle block an empty line and a TC-IN and TC-OUT is created automatically.

While clicking on the litte "plus" (Mouseover: "new subtitle block") before/after a subtitle block a new subtitle block appears. The following subtitle blocks move dynamically.

The user clicks on the "plus":
![add subtitle blocks](https://user-images.githubusercontent.com/59090140/85112640-3798b200-b216-11ea-9b90-52dfe6ac279f.jpg)

A new subtitle block with an empty line and automatically created TC-IN and -OUT appears:
![add subtitle blocks after](https://user-images.githubusercontent.com/59090140/85114091-aa0a9180-b218-11ea-9f87-63b9bdace562.jpg)

**Comment by tairt** [comment]
@mfinger-irt One question is about the gap between two subtitles. I propose a gap that corresponds to 1 frame (so 40ms if you have 25fps).

**Comment by tairt** [comment]
@mfinger-irt A good content structure for adding a subtitle would be as follows: 

```xml
<p....>
  <span>placeholder</span>
</p>
```

The following would also be good but we can not use it for the moment because there is no way to delete a subtitle line 

```xml
`<p....>
  <span>placeholder</span><br />
  <span>placeholder</span>
</p>
```

**Comment by tairt** [comment]
@mfinger-irt A tricky question is what style attributes should be added to the new `<p>` and `<span>` element. At the moment only the style attributes that are present at parsing/inserting time can be edited. So, if for example, if the `color` attribute is not present at a `<span>` when a new subtitle block is added, text color can not be changed on the text-level.

It may be good to provide the possibility to add a TTML template where a user can specify how the content structure and application of style attribute should look like. For the moment this could be a static template that is in the repository but in the end, there may be the option to provide the template in the custom folder.

The alternative would be to specify all possible style attributes for `<p>` and `<span>` elements. But in this case, inherited values (e.g. from `<div>` or `<body>`) would be overwritten.

**Comment by tairt** [comment]
The template approach could also be a good solution to get the right choice to add a new region for the subtitle block.

**Comment by tairt** [comment]
@LauraEhlis In the UI I think that the "plus" sign should be highlighted visually so that you can immediately see that you have the option to add subtitles. Possibly it can be set in bold (as the "x" for the deletion of subtitles) and the font could be a bit bigger.
