### ISSUE TITLE
Add subtitle lines

### ISSUE THREAD

**Issue by LauraEhlis** [IRT-Open-Source/imsced#105]
The user is able to add new subtitle lines at any position. 

While clicking on the litte "plus" (Mouseover: "new subtitle line") a new subtitle line appears after the corresponding line. The following subtitle blocks move dynamically.

The user clicks on the "plus":

![add subtitle line before](https://user-images.githubusercontent.com/59090140/85551136-fba08b00-b621-11ea-9ddb-173f74010cd9.jpg)

A new subtitle line appears:

![add subtitle line after](https://user-images.githubusercontent.com/59090140/85551147-ff341200-b621-11ea-990b-5e5583691a15.jpg)

**Comment by tairt** [comment]
Resolved by 22775e5
