### ISSUE TITLE
Add time-offsett parameter for STL Import

### ISSUE THREAD

**Issue by tairt** [IRT-Open-Source/imsced#11]
It is very common that timecodes in STL files are based on a timecode that is greater than `00:00:00:00". Often the assumption is a program start-timecode in the related media asset of `10:00:00:00`. 

IMSC and the subsets EBU-TT-D and EBU-TT-D-Basic-DE are using media-based time expression where the referenced timebase for a related media-file is always `0s`. If therefore the SMPTE timecode `10:00:00:00` is translated to the media time expession `10:00:00.000` it would refer to the 10th hour of the playtime of the related media although it should actually reference the start of the media.

It should, therefore, be possible for the user to indicate the "time offset" of the imported STL file (e.g. `10:00:00:00`. This offset needs then be subtracted from all timecodes in the imported subtitle file.

**Comment by tairt** [comment]
Resolved in release 0.4.0

**Comment by yurimkr** [comment]
resolved by f09e941a97f8381ff08007fc419d3f42b0b6c730
