### ISSUE TITLE
UI: Add navigation bar

### ISSUE THREAD

**Issue by LauraEhlis** [IRT-Open-Source/imsced#12]
Main features should be placed on the top of the screen. In the navigation bar the user can upload videos, subtitles and open extra services (e g. burn-in). 
On the right side of the upper menu there should be a settings menu where the user can change different settings. 

![IMG_2682](https://user-images.githubusercontent.com/59090140/71260141-6521a300-233a-11ea-95a8-6d0d0d984782.jpg)

**Comment by tairt** [comment]
Fixed in release 0.4.0

**Comment by yurimkr** [comment]
resolved by 8ca4498ac3a52eee700cced3cf11d9b5dc2826b6
