### ISSUE TITLE
UI: Change component order in the main screen

### ISSUE THREAD

**Issue by LauraEhlis** [IRT-Open-Source/imsced#13]
- Video-Player on the left side
- Subtitle Editor on the right side
- Titles on the top
- Playtime below the Video-Player

![IMG_2682](https://user-images.githubusercontent.com/59090140/71261626-1e35ac80-233e-11ea-8a0a-41804427a4c4.jpg)

**Comment by tairt** [comment]
Fixed in release 0.4.0
