### ISSUE TITLE
UI: Move menu to position subtitles

### ISSUE THREAD

**Issue by LauraEhlis** [IRT-Open-Source/imsced#15]
The position menu should be placed below the video and subtitle area. User can either insert style information or position (region). In this menu he can select a region or add a new region. There are also two buttons to allow dragging and resizing with the mouse.

**Comment by tairt** [comment]
Fixed in release 0.4.0

**Comment by yurimkr** [comment]
resolved by d8bf384ef856d6a1e6ddce7b621e6f44a96e2fce
