### ISSUE TITLE
Replace UI to manipulate color values

### ISSUE THREAD

**Issue by tairt** [IRT-Open-Source/imsced#17]
- The input of hex values as color information is not very user  friendly. Therefore this should be replaced by a color picker UI.

- The manipulation of the alpha channel for transparency can be left   out for the moment as the HTML color picker UI does not support   that.

**Comment by tairt** [comment]
Fixed in release 0.4.0

**Comment by yurimkr** [comment]
resolved by 54835c43b4f03889cf9973ccf124198586b1cdd5
