### ISSUE TITLE
Re-formatting config menu

### ISSUE THREAD

**Issue by tairt** [IRT-Open-Source/imsced#18]
Sections that show different config groups need to be  formatted accordingly.

**Comment by tairt** [comment]
Fixed in release 0.4.0

**Comment by yurimkr** [comment]
resolved by 
-  27507271c71bd5e4ff8d007fff2daba81564503b
-  ac9aad58381e33c0b7cdf74564443f1dc0eb230b
-  73eba802407cd8cf0f9fd46e2778949071c8bded
