### ISSUE TITLE
Bug: Emoji insertion using browser plugins

### ISSUE THREAD

**Issue by tairt** [IRT-Open-Source/imsced#26]
When an Emoji is not added using the keyboard but by a browser plugin the preview is not updated immediately and the new emoji is not seen. It needs a keyboard action (e.g. inserting a space) so that the preview updates.

**Comment by yurimkr** [comment]
The preview is also not updated when the content pasted over mouse/pop-up menu

**Comment by tairt** [comment]
@yurimkr The copy and paste problem is a separate issue and I will open another issue for this problem.

**Comment by tairt** [comment]
Investigation of the issues has shown that the insertion of emojis using plugins (e.g. by firefox emoji plugins), do not use standard patterns, therefore it is not possible at the moment to find a generic solution for this. We may want to implement an emoji picker as feature of the editor itself. This will be a separate feature issue. Closing this issue as won't fix.
