### ISSUE TITLE
support ruby features

### ISSUE THREAD

**Issue by mfinger-irt** [IRT-Open-Source/imsced#5]
All features related to "ruby" should be implemented.
This includes: 
https://www.w3.org/TR/ttml2/#style-attribute-ruby
https://www.w3.org/TR/ttml2/#style-attribute-rubyAlign
https://www.w3.org/TR/ttml2/#style-attribute-rubyPosition
https://www.w3.org/TR/ttml2/#style-attribute-rubyReserve
https://www.w3.org/TR/ttml2/#style-attribute-shear

**Comment by tairt** [comment]
(Partly) resolved by e6e704c

**Comment by mfinger-irt** [comment]
The following attributes are currently supported: 

- ruby -> full support

- rubyAlign -> only partly supported by the browser (Firefox only!)

- rubyPosition -> only partly supported by the browser (Firefox only!)

- shear -> full support

rubyReserve is currently not supported by us, because the structure differs from the other attributes.
