### ISSUE TITLE
Add unsupported style and parameter attributes to the export 

### ISSUE THREAD

**Issue by tairt** [IRT-Open-Source/imsced#63]
Not all IMSC/TTML style and parameter attributes are supported yet. If an input file contains unsupported attributes, they should be at least be exported with an equivalent value compared to original file.

**Comment by yurimkr** [comment]
following attributes added to the export:
- overflow
- padding
- position
- ruby
- rubyAlign
- rubyPosition
- rubyReserve
- textCombine
- textDecoration
- shear
- linePadding
- disparity (still not supported at imscJS)
