### ISSUE TITLE
Add check for characters per line and reading speed

### ISSUE THREAD

**Issue by mfinger-irt** [IRT-Open-Source/imsced#69]
So far there are no checks regarding the reading speed and the number of characters per line. 
The following should be implemented: 

- user should be able to configure the permitted number of characters per line and the reading speed

- the editor should take both values into account to calculate the subtitle duration

- the editor should give visual feedback if values do not meet the configured requirements

**Comment by LauraEhlis** [comment]
![check for caracters per line visual feedback](https://user-images.githubusercontent.com/59090140/82447874-2cccef00-9aa9-11ea-96ec-4a4d2a87b810.jpg)

- numbers on the right describe the maximum number of characters per line (37) and the actual number of characters (04)
- if the maximum number of characters ist exceeded, the numbers are marked in red and the text line "too many characters per line" appears
- if the number of characters is ok, it is marked in green and there is no text line

**Comment by tairt** [comment]
This issue was split up in several issues (e.g. https://github.com/IRT-Open-Source/imsced/issues/81) and will, therefore, be closed.
