### ISSUE TITLE
Synchronous step from video to subtitle

### ISSUE THREAD

**Issue by LauraEhlis** [IRT-Open-Source/imsced#74]
**Case 1:** video paused

If the user changes the video-timecode while clicking in the video bar, the corresponding subtitle appears in the user's field of view and the cursor jumps at the end of the first line of the corresponding subtitle. The corresponding subtitle block is shown in bold and the first line is framed.  

![synchronous step from video to subtitle case 1](https://user-images.githubusercontent.com/59090140/82922557-09f37c80-9f7a-11ea-9e09-f2a9937936aa.png)

**Case 2:** video in playback mode

If during the playback of the video the timecode coincide with the begin-timecode of one or more subtitle blocks, the cursor jumps at the end of the first line of the corresponding subtitle. (and the corresponding subtitle block is shown in bold and the first line is framed) 
If the timecode of the video coincide with the end-timecode of one or more subtitle blocks or the video-timecode is higher than the end-timecode of the corresponding subtitle, the subtitle block is no longer in the focus and the cursor is not in one of the subtitle lines anymore. 

![synchronous step from video to subtitle case 2](https://user-images.githubusercontent.com/59090140/82922434-e03a5580-9f79-11ea-8fc0-87247993f215.png)

**Comment by tairt** [comment]
There is an issue with the browser Firefox that blocks implementation for a dynamic seek using the timeline slider of the native browser control bar. Therefore the focus is only set according to the current time when the video is paused.

At the moment it is not planned to improve it further but the issue can be re-opened when the situation or the implementation context change.
