### ISSUE TITLE
synchronous step from subtitle to video

### ISSUE THREAD

**Issue by LauraEhlis** [IRT-Open-Source/imsced#75]
If the subtitle is on focus, the playback position of the video is set on the begin-timecode of the  subtitle. During editing the video is paused.

![synchronous step from subtitle to video](https://user-images.githubusercontent.com/59090140/82924488-b5053580-9f7c-11ea-8657-8dd708605d72.png)

**Comment by tairt** [comment]
@LauraEhlis I assume that when the input field to edit the subtitle loose focus again, the video needs to be restarted manually?

**Comment by tairt** [comment]
> @LauraEhlis I assume that when the input field to edit the subtitle loose focus again, the video needs to be restarted manually?

Checked with @LauraEhlis, assumption was correct.

**Comment by tairt** [comment]
Feature was already implemented in previous releases.
