### ISSUE TITLE
Save and load subtitle guidelines

### ISSUE THREAD

**Issue by LauraEhlis** [IRT-Open-Source/imsced#76]
All Settings that concern subtitle guidelines can be saved in a local file. The file can be loaded.
There must be a feedback ("settings saved").

![save and load subtitle guidelines](https://user-images.githubusercontent.com/59090140/83002582-871c0180-a00d-11ea-9699-92f42b14b3bb.jpg)

**Comment by tairt** [comment]
@LauraEhlis How do you know that this operations only apply to the guidline settings?

**Comment by LauraEhlis** [comment]
Yes, maybe it's better to place the operations directly to the subtitle guidelines:
![save and load subtitle guidelines 2](https://user-images.githubusercontent.com/59090140/83008054-dd407300-a014-11ea-8fae-3fd554cccd41.jpg)

**Comment by tairt** [comment]
The UI items to save and load the settings can also be placed in the subtitle settings area that opens after the "headline" for subtitle guidelines are clicked.

**Comment by LauraEhlis** [comment]
as an alternative:

![Save-Load subtitle guidelines](https://user-images.githubusercontent.com/59090140/83148861-bc058280-a0f9-11ea-8462-a10cfe1ba115.jpg)

**Comment by tairt** [comment]
The requested functionality is implemented. UI will be implemented at a later stage, therefore the issue is kept open.
