### ISSUE TITLE
Configuration number of characters per line

### ISSUE THREAD

**Issue by LauraEhlis** [IRT-Open-Source/imsced#77]
The user can define how many characters every line should maximal include. (A line is defined as a string of characters without a line-break)

![configuration number of characters per line](https://user-images.githubusercontent.com/59090140/83007569-2c39d880-a014-11ea-9093-9e531bc0b0fe.jpg)

**Comment by tairt** [comment]
@LauraEhlis I think that there should not be the option to conditionally include or exclude whitespaces or punctuation marks. At least for the moment there only a fixed option. The tolerated deviation is also not a feature we should include at this point in time.

**Comment by LauraEhlis** [comment]
![configuration number of characters per line](https://user-images.githubusercontent.com/59090140/83147696-55cc3000-a0f8-11ea-9e1e-db9911d1d593.jpg)

**Comment by tairt** [comment]
The requested functionality is implemented. UI will be implemented at a later stage, therefore the issue is kept open.

**Comment by tairt** [comment]
The UI part of this issue has moved to https://github.com/IRT-Open-Source/imsced/issues/109. Otherwise, the core requirement of this issue has been met and it can be closed.
