### ISSUE TITLE
Configuration number of lines per subtitle

### ISSUE THREAD

**Issue by LauraEhlis** [IRT-Open-Source/imsced#78]
The user can define how many lines every subtitle should maximal include. The default value is 2 lines.

![configuration number of lines per subtitle](https://user-images.githubusercontent.com/59090140/83147403-ece4b800-a0f7-11ea-8538-e4c82057216b.jpg)

**Comment by tairt** [comment]
The requested functionality is implemented. UI will be implemented at a later stage, therefore the issue is kept open.

**Comment by tairt** [comment]
The UI part of this issue has moved to https://github.com/IRT-Open-Source/imsced/issues/109. Otherwise, the core requirement of this issue has been met and it can be closed.
