### ISSUE TITLE
Warning: To many subtitle lines per subtitle block

### ISSUE THREAD

**Issue by tairt** [IRT-Open-Source/imsced#79]
For every subtitle block that exceeds the preconfigured maximum number of lines per subtitle block a warning is shown.

**Comment by LauraEhlis** [comment]
![Warning too many subtitle lines per subtitle block](https://user-images.githubusercontent.com/59090140/83017908-bd18b000-a024-11ea-8080-9d982fb9a19c.jpg)

**Comment by tairt** [comment]
The requested functionality is implemented. UI will be implemented at a later stage, therefore the issue is kept open.

**Comment by tairt** [comment]
The UI part of this issue has moved to https://github.com/IRT-Open-Source/imsced/issues/110. Otherwise, the core requirement of this issue has been met and it can be closed.
