### ISSUE TITLE
Notice: preset number of characters per line is exceeded

### ISSUE THREAD

**Issue by LauraEhlis** [IRT-Open-Source/imsced#80]
If the preset number of characters per line is exceeded the editor issues a warning.
 
The numbers on the right of every subtitle describe the maximum number of characters per line (37) and the actual number of characters (04).
If the maximum number of characters ist exceeded, the numbers are marked in red.
If the number of characters is ok, it is marked in green and there is no text line.

![Notice preset number of characters per line is exceeded](https://user-images.githubusercontent.com/59090140/83015921-770e1d00-a021-11ea-9611-1a5fcc8d2e5a.jpg)

If values do not meet the configured requirements there is a red light on the right side and an error message. If there are more than one errors a "+" appears. The user can click on the "+" and all error messages appear.

![Notice preset number of characters per line is exceeded](https://user-images.githubusercontent.com/59090140/83154053-f5d98780-a0ff-11ea-993d-eb1767de778f.jpg)

**Comment by tairt** [comment]
The requested functionality is implemented. UI will be implemented at a later stage, therefore the issue is kept open.

**Comment by tairt** [comment]
The UI part of this issue has moved to https://github.com/IRT-Open-Source/imsced/issues/109. Otherwise, the core requirement of this issue has been met and it can be closed.
