### ISSUE TITLE
Configuration: Reading Speed in Characters per Second

### ISSUE THREAD

**Issue by tairt** [IRT-Open-Source/imsced#81]
The imscED user can configure an average reading speed for the target audience of his subtitles. The reading speed includes all characters displayed characters (e.g. also spaces, special characters, and punctuation marks).

**Comment by LauraEhlis** [comment]
![Configuration Reading speed in characters per second](https://user-images.githubusercontent.com/59090140/83019119-b854fb80-a026-11ea-8501-15a789e95975.jpg)

**Comment by tairt** [comment]
The requested functionality is implemented. UI will be implemented at a later stage, therefore the issue is kept open.

**Comment by tairt** [comment]
The UI part of this issue has moved to https://github.com/IRT-Open-Source/imsced/issues/109. Otherwise, the core requirement of this issue has been met and it can be closed.
