### ISSUE TITLE
Configuration: Minimal duration

### ISSUE THREAD

**Issue by tairt** [IRT-Open-Source/imsced#83]
The imscED user can configure the minimal duration of a subtitle block. The unit is "seconds".

**Comment by LauraEhlis** [comment]
![Configuration Minimal duration](https://user-images.githubusercontent.com/59090140/83146715-fd486300-a0f6-11ea-9723-461ca17a788d.jpg)

**Comment by tairt** [comment]
The requested functionality is implemented. UI will be implemented at a later stage, therefore the issue is kept open.

**Comment by tairt** [comment]
The UI part of this issue has moved to https://github.com/IRT-Open-Source/imsced/issues/109. Otherwise, the core requirement of this issue has been met and it can be closed.
