### ISSUE TITLE
Information: Characters per line

### ISSUE THREAD

**Issue by tairt** [IRT-Open-Source/imsced#87]
For every subtitle block the numbers of characters for each line are shown. The base of the calculation is the same that leads to the preconfigured valued for the maximum number of characters per line.

**Comment by LauraEhlis** [comment]
![Information characters per line](https://user-images.githubusercontent.com/59090140/83145928-d8072500-a0f5-11ea-87d8-20bbb063d22b.jpg)

**Comment by tairt** [comment]
The requested functionality is implemented. UI will be implemented at a later stage, therefore the issue is kept open.

**Comment by tairt** [comment]
@LauraEhlis I think also the UI part of this issue has been met. Therefore I will close it. Re-open if something is missing.
