### ISSUE TITLE
Configuration: warnings for subtitle restrictions 

### ISSUE THREAD

**Issue by LauraEhlis** [IRT-Open-Source/imsced#88]
The user can activate/deactivate warnings for subtitle restrictions. 

![Configuration warnings for subtitle restrictions](https://user-images.githubusercontent.com/59090140/83145140-a6da2500-a0f4-11ea-95f7-0f673da821b7.jpg)

**Comment by tairt** [comment]
The requested functionality is implemented. UI will be implemented at a later stage, therefore the issue is kept open.

**Comment by tairt** [comment]
The UI part of this issue has moved to #109. Otherwise, the core requirement of this issue has been met and it can be closed.
