### ISSUE TITLE
Configuration: visualisation of duration

### ISSUE THREAD

**Issue by LauraEhlis** [IRT-Open-Source/imsced#89]
The user can activate/deactivate the visualisation of the duration.

![visualisation of duration](https://user-images.githubusercontent.com/59090140/83145512-2b2ca800-a0f5-11ea-9bdf-50d1e61753b3.jpg)

**Comment by xchange11** [comment]
The requested functionality is implemented. UI will be implemented at a later stage, therefore the issue is kept open.

**Comment by tairt** [comment]
The requested functionality is implemented. UI will be implemented at a later stage, therefore the issue is kept open.

**Comment by tairt** [comment]
The UI part of this issue has moved to https://github.com/IRT-Open-Source/imsced/issues/109. Otherwise, the core requirement of this issue has been met and it can be closed.
