### ISSUE TITLE
Delete subtitle blocks

### ISSUE THREAD

**Issue by LauraEhlis** [IRT-Open-Source/imsced#92]
While clicking on the "x" (upper right corner of every subtitle block) the user can delete subtitle blocks. 
The subtitle block disappears and the TC-Ins and TC-Outs of the previous and following subtitle blocks remain uncharged. It's also possible that there is no subtitle block. There must be a configurable shortcut for this feature. 

![Delete subtitle blocks](https://user-images.githubusercontent.com/59090140/83632198-29546000-a59f-11ea-957e-01ee9adb9c34.jpg)

**Comment by tairt** [comment]
@LauraEhlis 

> If the user only wants to delete one subtitle and not the whole subtitle block he has to click on the "x" on the right side of the corresponding subtitle. In this case the first subtitle disappears and the second subtitle jumps to the first position.
There must also be a configurable shortcut for this feature.

This is actually a separate requirement and I would open a different issue for it.

**Comment by tairt** [comment]
@LauraEhlis It may be good to have a modal popup where you need to confirm the deletion of the subtitle block. What do you think? The deleted subtitle block is not re-discoverable (at least for the moment this is not a requirement).

**Comment by LauraEhlis** [comment]
We must generally consider if there should be an undo and redo function.

**Comment by LauraEhlis** [comment]
As long as there is no undo and redo function the user has to confirm the deletion of the subtitle block. 
The popup "Are you sure to delete this subtitle block?" appears if the user clicks on the "x". He confirms the deletion of the subtitle while clicking "delete". The popup and the subtitle block disappear and the TC-Ins and TC-Outs of the previous and following subtitle blocks remain uncharged. 
If the user clicks "cancel" the popup disappears and the subtitle blocks stay the same (it's also possible to click outside the popup).

![Delete subtitle confirm](https://user-images.githubusercontent.com/59090140/83765315-4cecd880-a67b-11ea-92c7-d55e61aa311b.jpg)

**Comment by tairt** [comment]
Resolved by 2233b7e
