### ISSUE TITLE
Changing start and stop times of subtitles

### ISSUE THREAD

**Issue by LauraEhlis** [IRT-Open-Source/imsced#93]
The user can individually change the start and stop time of every subtitle.

**Comment by tairt** [comment]
@LauraEhlis One question: initially the subtitles are in an ascending order based on the begin time. If you change the begin time: how does this affect the order of the subtitles that are currently displayed? If subs should be re-ordered: when does the re-ordering take place? After the user leaves the edit field of the time value?

**Comment by tairt** [comment]
@LauraEhlis Another question: how does the state of video position change during/after time value editing

**Comment by tairt** [comment]
@LauraEhlis Another issue is when a user sets the begin time to value that is equal or later than the end time. Either an error message is shown or it is not possible to extend the end time beyond the begin time or vice versa to change the end time so that it is earlier than the begin time...

**Comment by LauraEhlis** [comment]
If the user changes the start or stop time the order of the subtitles that are currently displayed doesn't change. But there is a "Refresh-Icon". While clicking on this icon the subtitles are re-ordered. The focus stays on the subtitle which was last edited.

**Comment by LauraEhlis** [comment]
> @LauraEhlis One question: initially the subtitles are in an ascending order based on the begin time. If you change the begin time: how does this affect the order of the subtitles that are currently displayed? If subs should be re-ordered: when does the re-ordering take place? After the user leaves the edit field of the time value?

If the user changes the start or stop time the order of the subtitles that are currently displayed doesn't change. But there is a "Refresh-Icon". While clicking on this icon the subtitles are re-ordered. The focus stays on the subtitle which was last edited.

**Comment by LauraEhlis** [comment]
> @LauraEhlis Another issue is when a user sets the begin time to value that is equal or later than the end time. Either an error message is shown or it is not possible to extend the end time beyond the begin time or vice versa to change the end time so that it is earlier than the begin time...

Yes, it shouldn't be possible to extend the end time beyond the begin time or vice versa and there should also be an error message.

**Comment by mfinger-irt** [comment]
> > @LauraEhlis Another issue is when a user sets the begin time to value that is equal or later than the end time. Either an error message is shown or it is not possible to extend the end time beyond the begin time or vice versa to change the end time so that it is earlier than the begin time...
> 
> Yes, it shouldn't be possible to extend the end time beyond the begin time or vice versa and there should also be an error message.

Should the times be automatically changed to guarantee there is no duration less than 0s? And if so should there be another error message independent of the warning for minimum time?

**Comment by tairt** [comment]
If we have for example a subtitle block with `begin=2s` and with `end=4s`. The question is what happens if the user wants to change the begin time to `4s` or to `4.1s`. As I understand the proposed solution the begin time will not go beyond `3.960s` (i.e. will be automatically corrected to this value). 

Of course, this value does also not lead to a desirable outcome (with a duration of 40 ms). It is also the question if an error message should be shown (as @lauraEhlis proposed). If the value is corrected it is afterwards (at least technically) compliant. 

Possibly it is better to let the user change the value as desired and show an error message? I can imagine that a user might want to first change the begin time (e.g. to `4s` in the example) and then afterwards adjust the end time (e.g. to `6s`).

**Comment by LauraEhlis** [comment]
> If we have for example a subtitle block with `begin=2s` and with `end=4s`. The question is what happens if the user wants to change the begin time to `4s` or to `4.1s`. As I understand the proposed solution the begin time will not go beyond `3.960s` (i.e. will be automatically corrected to this value).
> 
> Of course, this value does also not lead to a desirable outcome (with a duration of 40 ms). It is also the question if an error message should be shown (as @LauraEhlis proposed). If the value is corrected it is afterwards (at least technically) compliant.
> 
> Possibly it is better to let the user change the value as desired and show an error message? I can imagine that a user might want to first change the begin time (e.g. to `4s` in the example) and then afterwards adjust the end time (e.g. to `6s`).

![wrong timecode](https://user-images.githubusercontent.com/59090140/85116354-767e3600-b21d-11ea-986c-e33d3531f4db.jpg)

**Comment by tairt** [comment]
Resolved by 2233b7e, 43416a8 and 9c5699f
