### ISSUE TITLE
Delete subtitle lines

### ISSUE THREAD

**Issue by LauraEhlis** [IRT-Open-Source/imsced#94]
If the user only wants to delete one subtitle line and not the whole subtitle block he has to click on the "x" on the right side of the corresponding subtitle line. In this case the first subtitle line disappears and the second subtitle line jumps to the first position.
There must also be a configurable shortcut for this feature.

![Delete subtitles](https://user-images.githubusercontent.com/59090140/83637441-ed71c880-a5a7-11ea-8f0a-8f0bff91fc08.jpg)

**Comment by tairt** [comment]
Resolved by 22775e5
