### ISSUE TITLE
Set focus on subtitle edit field when user action on subtitle block

### ISSUE THREAD

**Issue by tairt** [IRT-Open-Source/imsced#97]
If a user targets the UI element that corresponds to the subtitle block, the focus will be set on the end of the first line of the corresponding subtitle block. The primary user event is a mouse click.

**Comment by LauraEhlis** [comment]
![Set focus on subtitle edit field when user action on subtile block](https://user-images.githubusercontent.com/59090140/85116099-15eef900-b21d-11ea-9d14-a243f3a66b31.jpg)
